# -*- coding: utf-8 -*-
"""textgeneration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IsdrnEkxl2tcNVr3VfvoWQa8dJ2lpYQ2
"""

!pip install transformers torch

from transformers import pipeline
generator=pipeline("text-generation",model="gpt2")
prompt = "stranger things in NETFLIX"
result = generator(prompt,max_length=50,num_return_sequences=1)
print("stranger things in NETFLIX:")
print(result[0]['generated_text'])